server:
  port: 8888 # Puerto para el Config Server

spring:
  application:
    name: config-server # Nombre para Eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SHF0987654321/monorepo-config # ¡Esta es la línea clave! Apunta a tu repositorio Git local.
          username: SHF0987654321 # <-- Tu nombre de usuario de GitHub
          password: ${CONFIG_REPO_PAT} # <-- Tu token de acceso personal de GitHub
        clone-on-start: true # Clona el repositorio al iniciar el Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Apunta a tu servidor Eureka
  instance:
    hostname: localhost
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.eclipse.jgit: DEBUG # JGit es la librería que usa Spring para interactuar con Git