server:
  port: 8888 # Puerto para el Config Server

spring:
  application:
    name: config-server # Nombre para Eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SHF0987654321/monorepo-config.git # ¡Esta es la línea clave! Apunta a tu repositorio Git local.
          username: SHF0987654321 # <-- Tu nombre de usuario de GitHub
          password: ${GITHUB_CONFIG_REPO_PAT} # <-- Tu token de acceso personal de GitHub

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Apunta a tu servidor Eureka
  instance:
    hostname: localhost