server:
  port: 8761 # Puerto estándar para Eureka Server

spring:
  application:
    name: eureka-server # Nombre de la aplicación, importante para Eureka y Config

eureka:
  instance:
    hostname: localhost # Para desarrollo local, Eureka se auto-registra como localhost
  client:
    register-with-eureka: false # Esto es un Eureka Server, NO necesita registrarse a sí mismo
    fetch-registry: false      # Esto es un Eureka Server, NO necesita obtener el registro de otros
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # URL de sí mismo
