server:
  port: 8080 # Puerto para el Gateway, puedes usar 80 para un puerto estándar HTTP

spring:
  application:
    name: gateway-server # Nombre con el que se registrará en Eureka
  cloud:
    gateway:
      routes:
        - id: servicio-usuarios # ID único para esta ruta
          uri: lb://SERVICIO-USUARIOS # Usar "lb" (load balancer) con Eureka para encontrar el servicio de usuarios
          predicates:
            - Path=/usuarios/** # Enrutará peticiones que comiencen con /usuarios/ a este servicio

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # URL del servidor Eureka
