server:
  port: 0
spring:
  application:
    name: servicio-usuarios
  
  datasource:
    url: ${DB_USER} # ¡MUY IMPORTANTE: Reemplaza con tu Endpoint real de RDS!
    username: ${DB_USER_USERNAME}  # Tu nombre de usuario maestro de RDS
    password: ${DB_USER_PASSWORD} # ¡MUY IMPORTANTE: Reemplaza con tu contraseña maestra de RDS!
    driver-class-name: ${DB_CLASS_USER} # Driver para MySQL 8.x
  
  jpa:
    hibernate:
      ddl-auto: update # Crea/actualiza el esquema de la DB automáticamente
    show-sql: true # Muestra las consultas SQL en la consola
    properties:
      hibernate:
        format_sql: true # Formatea el SQL para que sea legible

  config:
    import: optional:configserver:discovery/

  cloud:
    config:
      discovery:
        enabled: true          # ← Habilita que use Eureka para buscar el config server
        service-id: CONFIG-SERVER  # ← Nombre con el que el config-server está registrado en Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: $(spring.application.name):${random.value}